$TTL    604800 ; 1 week
@       IN      SOA     dns-primary.example.com. admin.example.com. (
                            2024042001      ; Serial (Date + Counter)
                            604800          ; Refresh
                            86400           ; Retry
                            2419200         ; Expire
                            604800 )        ; Negative Cache TTL

; Name Servers
@       IN      NS      dns-primary.example.com.
@       IN      NS      dns-secondary.example.com.

; Mail Exchanger (SMTP)
@       IN      MX      10 mail.example.com.

; Host Records
dns-primary     IN      A       192.168.56.10
dns-primary     IN      AAAA    fd00:cafe:beef::10
dns-secondary   IN      A       192.168.56.11
dns-secondary   IN      AAAA    fd00:cafe:beef::11
dhcp            IN      A       192.168.56.13
dhcp            IN      AAAA    fd00:cafe:beef::13

; SMTP Server (IP-SMTP / IPv6-SMTP)
mail            IN      A       192.168.56.12   ; A -> IP-SMTP
mail            IN      AAAA    fd00:cafe:beef::12 ; AAAA -> IPv6-SMTP

; SPF Record (Sender Policy Framework)
@       IN      TXT     "v=spf1 mx a:mail.example.com -all"

; DKIM Record (DomainKeys Identified Mail)
; This will be generated by OpenDKIM on the mail server. You need to get the public key
; and create a TXT record like: selector._domainkey IN TXT "v=DKIM1; k=rsa; p=YOUR_PUBLIC_KEY_HERE"
; Placeholder:
default._domainkey IN      TXT     "v=DKIM1; h=sha256; k=rsa; "
    smtp:         "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsqH6U1yVRt3zXYdraUvpco3SFYXJSWu754cXLv4LB4tBIr8HArdmsOt19/ZpF3eDkYlUOLczN5aw69/WtHYokTAa6uKe+XrMNo+tM1wNDuIYab2UyV22/wVN+bmykLU+PbrjCvfDXj7mtdkRBJrFUWvcn9dXvKB+GfuTe/lvjUsyMFc7ozB19QLP3GYOm5KMDwoFiqtBnzvg9s"
    smtp:         "+Ww0TE53bsAQK19YQNm+ElqAGnXLSc+iZ88OZMTA009Lu0b2L+tcIFzqfGvReoOdXi7Jj05bYRau4CovKstluAULKnVUAMZWNKRAVJVg5BYEfDvGs/FNDiN28Nv6kP59LSoqlC5QIDAQAB" ; Key needs to be added from mail server

; DMARC Record (Domain-based Message Authentication, Reporting & Conformance)
_dmarc  IN      TXT     "v=DMARC1; p=quarantine; rua=mailto:dmarc-reports@example.com; ruf=mailto:dmarc-reports@example.com; fo=1"
